apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-api-ingress
spec:
  rules:
    - http:
        paths:
          - path: /employees
            pathType: Prefix
            backend:
              service:
                name: employee-api
                port:
                  number: 8080
