apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  clusterIP: None # headless for StatefulSet
  selector:
    app: mongo
