apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_INITDB_DATABASE: employeedb
  APP_NAME: "employee-api"
  LOG_LEVEL: "INFO"
  MONGO_LOG_LEVEL: "INFO"
  mongo-init.js: |
    db = db.getSiblingDB(process.env.MONGO_INITDB_DATABASE);
    db.createUser({
      user: process.env.MONGO_APP_USERNAME,
      pwd: process.env.MONGO_APP_PASSWORD,
      roles: [
        {
          role: 'readWrite',
          db: process.env.MONGO_INITDB_DATABASE
        }
      ]
    });
