apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: shubhendumishra/employee-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_INITDB_DATABASE
              value: "employeedb"
            - name: APP_NAME
              value: "employee-api"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MONGO_LOG_LEVEL
              value: "INFO"
            - name: MONGO_APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_APP_USERNAME
            - name: MONGO_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_APP_PASSWORD
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI

---
apiVersion: v1
kind: Service
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  type: ClusterIP
  selector:
    app: employee-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
