apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: employee-api-cert
spec:
  secretName: employee-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - shubhendu.dev
